

spring.datasource.url=jdbc:Mysql://localhost/db_springboot_backend
spring.datasource.username=root
spring.datasource.password=mysql
##Driver de mysql el conector 
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

##Dialecto para el jpa innoDB cual es el motor de la base de datos 
##Con el soporte a integridad referencial  
spring.jpa.database-platform=org.hibernate.dialect.MySQL57Dialect

##Ahora vamos a configurar para que las tablas de las bases de datos 
##Se creen de forma automatica a partir de las clase entity de la metadata

spring.jpa.hibernate.ddl-auto=update

##Sql nativas
logging.level.org.hibernate.SQL=debug

server.port=8090